export LLVM_DIR="/home/hugh/.cache/ti-build-cache/llvm-22.1.0-x86-202603120808"
export VULKAN_SDK="/home/hugh/.cache/ti-build-cache/vulkan-1.4.321.1/x86_64"
export PATH="/home/hugh/.cache/ti-build-cache/vulkan-1.4.321.1/x86_64/bin:/home/hugh/ais/seagull/quadrants/.venv/bin:/home/hugh/.local/bin:/home/hugh/bin:/home/hugh/.local/bin:/home/hugh/bin:/home/hugh/.local/bin:/home/hugh/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin"
export LD_LIBRARY_PATH="/home/hugh/.cache/ti-build-cache/vulkan-1.4.321.1/x86_64/lib"
export VK_LAYER_PATH="/home/hugh/.cache/ti-build-cache/vulkan-1.4.321.1/x86_64/share/vulkan/explicit_layer.d"
export SCCACHE_LOG="error"
export SCCACHE_DIR="/home/hugh/.cache/ti-build-cache/sccache-v0-10-0/cache"
export SCCACHE_CACHE_SIZE="40G"
export SCCACHE_STARTUP_TIMEOUT="30"
export SCCACHE_IDLE_TIMEOUT="0"
export QUADRANTS_CMAKE_ARGS="-DCLANG_EXECUTABLE=/usr/bin/clang-20 -DCMAKE_CXX_COMPILER_WORKS=1 -DCMAKE_C_COMPILER_LAUNCHER=/home/hugh/.cache/ti-build-cache/sccache-v0-10-0/bin/sccache -DCMAKE_CXX_COMPILER_LAUNCHER=/home/hugh/.cache/ti-build-cache/sccache-v0-10-0/bin/sccache"