"""Compile a GLSL helper library into a C++ header; requires glslang with --no-link support."""

import argparse
import struct
import subprocess
import tempfile
from pathlib import Path


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--input", type=Path, required=True)
    parser.add_argument("--symbol", required=True)
    parser.add_argument("--target-env", default="vulkan1.0")
    parser.add_argument("--output", type=Path, required=True)
    parser.add_argument("--compiler", default="glslangValidator")
    args = parser.parse_args()
    with tempfile.TemporaryDirectory() as tmp:
        binary = Path(tmp) / "shader.spv"
        subprocess.run(
            [args.compiler, "-V", "--target-env", args.target_env, "--no-link", "-Od", str(args.input), "-o", str(binary)],
            check=True,
        )
        data = binary.read_bytes()
    words = struct.unpack(f"<{len(data) // 4}I", data)
    header = f"""// Generated by shaders/compile_shader.py. Do not edit.
#pragma once
#include <cstdint>

namespace quadrants::lang::spirv {{
// clang-format off
inline constexpr uint32_t {args.symbol}[] = {{
"""
    for i in range(0, len(words), 8):
        header += "    " + ", ".join(f"0x{word:08x}" for word in words[i : i + 8]) + ",\n"
    header += "};\n// clang-format on\n}  // namespace quadrants::lang::spirv\n"
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(header)


if __name__ == "__main__":
    main()
