"""Regenerate the embedded workgroup library; requires glslang with --no-link support."""

import argparse
import hashlib
import struct
import subprocess
import tempfile
from pathlib import Path


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--compiler", default="glslangValidator")
    args = parser.parse_args()
    source = Path(__file__).with_name("workgroup.comp")
    with tempfile.TemporaryDirectory() as tmp:
        binary = Path(tmp) / "workgroup.spv"
        subprocess.run(
            [args.compiler, "-V", "--target-env", "vulkan1.0", "--no-link", "-Od", str(source), "-o", str(binary)],
            check=True,
        )
        data = binary.read_bytes()
    words = struct.unpack(f"<{len(data) // 4}I", data)
    digest = hashlib.sha256(source.read_text().encode()).hexdigest()
    header = f"""// Generated by shaders/generate_workgroup.py. Do not edit.
// GLSL source SHA256: {digest}
#pragma once
#include <cstdint>

namespace quadrants::lang::spirv {{
// clang-format off
inline constexpr uint32_t workgroup_helper_spv[] = {{
"""
    for i in range(0, len(words), 8):
        header += "    " + ", ".join(f"0x{word:08x}" for word in words[i : i + 8]) + ",\n"
    header += "};\n// clang-format on\n}  // namespace quadrants::lang::spirv\n"
    target = source.with_name("workgroup_spv.h")
    if args.check:
        if target.read_text() != header:
            raise SystemExit("Embedded workgroup library differs; regenerate it with the documented glslang version.")
    else:
        target.write_text(header)


if __name__ == "__main__":
    main()
