#!/bin/bash
# Run clang-tidy only on the AMDGPU-specific TUs in the compile database
# generated by 2_build.sh. The `files` positional to scripts/run_clang_tidy.py
# is a regex on the absolute file path; restricting to
# quadrants/(codegen|platform|rhi|runtime)/amdgpu/ means we analyze only the
# ~18 AMDGPU files instead of all ~300, while -header-filter scopes
# included-header diagnostics to the same directories.

set -ex

AMDGPU_RE="quadrants/(codegen|platform|rhi|runtime)/amdgpu/"

python ./scripts/run_clang_tidy.py \
    -clang-tidy-binary clang-tidy-14 \
    -p build \
    -header-filter="${PWD}/${AMDGPU_RE}" \
    -j"$(nproc)" \
    "${PWD}/${AMDGPU_RE}"
