from typing import Any

class CompoundType: ...

def matrix(n: int | None = ..., m: int | None = ..., dtype: Any = ...) -> Any: ...
def vector(n: int | None = ..., dtype: Any = ...) -> Any: ...
def struct(**kwargs: Any) -> Any: ...
