from typing import Any

class CompoundType:
    def from_kernel_struct_ret(self, launch_ctx: Any, index: tuple[Any, ...]) -> Any: ...
    def check_matched(self, other: Any) -> bool: ...
    def to_string(self) -> str: ...

def matrix(n: int | None = ..., m: int | None = ..., dtype: Any = ...) -> Any: ...
def vector(n: int | None = ..., dtype: Any = ...) -> Any: ...
def struct(**kwargs: Any) -> Any: ...
