#!/bin/bash
#
# Builds the pre-compiled fatbin for the graph_do_while condition kernel.
# Requires the CUDA toolkit (nvcc) to be installed.
#
# The output is a C header (condition_kernel_fatbin.h) containing the fatbin
# as a byte array, which is compiled into the quadrants binary. At runtime
# this lets us load the condition kernel without needing libcudadevrt.a on
# the user's system.
#
# Usage:
#   ./scripts/build_condition_kernel_fatbin.sh
#
# See docs/source/user_guide/building_cudagraph_conditional_fatbin.md

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
SRC="$REPO_ROOT/quadrants/runtime/cuda/condition_kernel.cu"
OUT_DIR="$REPO_ROOT/quadrants/runtime/cuda"
OBJ=$(mktemp /tmp/condition_kernel.XXXXXX.o)
FATBIN=$(mktemp /tmp/condition_kernel.XXXXXX.fatbin)

cleanup() { rm -f "$OBJ" "$FATBIN"; }
trap cleanup EXIT

SM_TARGETS=(
    -gencode=arch=compute_90,code=sm_90
    -gencode=arch=compute_120,code=sm_120
)

echo "Compiling $SRC ..."
nvcc -dc -rdc=true "${SM_TARGETS[@]}" "$SRC" -o "$OBJ"

echo "Device-linking with libcudadevrt ..."
nvcc -dlink "${SM_TARGETS[@]}" "$OBJ" -lcudadevrt -fatbin -o "$FATBIN"

echo "Generating C header ..."
python3 -c "
import sys
data = open('$FATBIN', 'rb').read()
out = open('$OUT_DIR/condition_kernel_fatbin.h', 'w')
out.write('// Auto-generated by scripts/build_condition_kernel_fatbin.sh\n')
out.write('// Do not edit manually. Regenerate with that script.\n')
out.write('//\n')
out.write('// Source: quadrants/runtime/cuda/condition_kernel.cu\n')
out.write(f'// Size: {len(data)} bytes\n\n')
out.write('#pragma once\n\n')
out.write('#include <cstddef>\n\n')
out.write('static const unsigned char kConditionKernelFatbin[] = {\n')
for i in range(0, len(data), 16):
    chunk = data[i:i+16]
    out.write('    ' + ', '.join(f'0x{b:02x}' for b in chunk) + ',\n')
out.write('};\n\n')
out.write(f'static const std::size_t kConditionKernelFatbinSize = {len(data)};\n')
out.close()
print(f'Wrote {out.name} ({len(data)} bytes)')
"

echo "Done."
