#!/usr/bin/env python3
"""Builds the pre-compiled bundled HSACO for the qd.checkpoint() yield-check kernel on AMDGPU.

Requires the AMD ROCm toolkit (hipcc) to be installed. Mirror of `scripts/build_checkpoint_yield_check_fatbin.py` (the
CUDA equivalent), with the very same "build-once, check in the generated header" pattern. The pre-Hopper CUDA / AMDGPU
`qd.checkpoint` lowering both insert this kernel inline in a flat (CUDA / HIP) graph after each yielding checkpoint's
last body kernel; the kernel self-gates on resume_point / yield_signal so the runtime does not need to host-orchestrate
per-checkpoint skips.

The output is a C header (checkpoint_yield_check_hsaco.h) that contains the bundled HSACO ("offload bundle" in clang
parlance) as a byte array, compiled into the quadrants binary. Then at runtime `hipModuleLoadData` takes the bundle and
selects the right per-arch HSACO for the current device, the same way `cuModuleLoadData` selects from a CUDA fatbin.

Usage:
    python scripts/build_checkpoint_yield_check_hsaco.py

The script must run on a machine with ROCm installed (it shells out to hipcc). Quadrants' CUDA fatbin scripts have the
same constraint: build offline on a box that has the toolkit, check in the generated header.

Default offload arches cover the main hardware quadrants currently runs on:

  - gfx90a  -- CDNA2  (MI200 / MI210 / MI250(X)).
  - gfx942  -- CDNA3  (MI300A / MI300X) -- the amdcloud box.
  - gfx1010 -- RDNA1  (Radeon RX 5700 / 5700 XT / Navi 10).
  - gfx1011 -- RDNA1  (Radeon Pro V520 / Navi 12) -- the AWS g4ad CI runner.
  - gfx1012 -- RDNA1  (Radeon RX 5500 XT / Navi 14).
  - gfx1030 -- RDNA2  (Radeon RX 6800 / 6900).
  - gfx1100 -- RDNA3  (Radeon RX 7900 XTX) -- the amddesktop box.
  - gfx1101 -- RDNA3  (Radeon RX 7800 XT / 7700 XT).
  - gfx1102 -- RDNA3  (Radeon RX 7600).
  - gfx1200 -- RDNA4  (Radeon RX 9070 GRE).
  - gfx1201 -- RDNA4  (Radeon RX 9070 / 9070 XT).
"""

import os
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
SRC = REPO_ROOT / "quadrants" / "runtime" / "amdgpu" / "checkpoint_yield_check.hip"
OUT_HEADER = REPO_ROOT / "quadrants" / "runtime" / "amdgpu" / "checkpoint_yield_check_hsaco.h"

OFFLOAD_ARCHES = [
    "gfx90a",
    "gfx942",
    "gfx1010",
    "gfx1011",
    "gfx1012",
    "gfx1030",
    "gfx1100",
    "gfx1101",
    "gfx1102",
    "gfx1200",
    "gfx1201",
]


def find_hipcc() -> str:
    hipcc = shutil.which("hipcc")
    if hipcc:
        return hipcc
    candidates = []
    if "ROCM_PATH" in os.environ:
        candidates.append(os.path.join(os.environ["ROCM_PATH"], "bin", "hipcc"))
    if "HIP_PATH" in os.environ:
        candidates.append(os.path.join(os.environ["HIP_PATH"], "bin", "hipcc"))
    candidates.append("/opt/rocm/bin/hipcc")
    for candidate in candidates:
        if Path(candidate).exists():
            return candidate
    sys.exit(
        "Error: hipcc not found. Install the AMD ROCm toolkit and add it to PATH, or set "
        "ROCM_PATH / HIP_PATH. This script must run on a machine with ROCm; see the header "
        "comment for the standard list of offload arches it targets."
    )


def run(cmd: list[str]) -> None:
    print(f"  {' '.join(cmd)}")
    subprocess.check_call(cmd)


def generate_header(bundle_path: Path, out_path: Path) -> None:
    bundle_data = bundle_path.read_bytes()
    header_lines = [
        "// Auto-generated by scripts/build_checkpoint_yield_check_hsaco.py",
        "// Do not edit manually. Regenerate with that script.",
        "//",
        "// Source: quadrants/runtime/amdgpu/checkpoint_yield_check.hip",
        f"// Offload arches: {', '.join(OFFLOAD_ARCHES)}",
        f"// Size: {len(bundle_data)} bytes",
        "",
        "#pragma once",
        "",
        "#include <cstddef>",
        "",
        "static const unsigned char kCheckpointYieldCheckKernelHsaco[] = {",
    ]
    # Wide layout (19 bytes / line ~= 120c) lines up with what pre-commit's clang-format would produce, so the CI
    # linter is happy without an extra `clang-format -i` pass on the regenerated header.
    for i in range(0, len(bundle_data), 19):
        chunk = bundle_data[i : i + 19]
        header_lines.append("    " + ", ".join(f"0x{b:02x}" for b in chunk) + ",")
    header_lines.append("};")
    header_lines.append("")
    header_lines.append(f"static const std::size_t kCheckpointYieldCheckKernelHsacoSize = {len(bundle_data)};")
    header_lines.append("")
    out_path.write_text("\n".join(header_lines), newline="\n")
    print(f"Wrote {out_path} ({len(bundle_data)} bytes)")


def main() -> None:
    hipcc = find_hipcc()

    with tempfile.TemporaryDirectory() as tmpdir:
        # `--genco` produces a single bundled code object (offload bundle) that `hipModuleLoadData` can demultiplex at
        # runtime. Multiple `--offload-arch` produce one HSACO per arch packed inside the bundle. The output is a single
        # file containing all archs; the HIP runtime picks the right one for the current device.
        bundle_path = Path(tmpdir) / "checkpoint_yield_check.hsaco"
        cmd = [
            hipcc,
            "--genco",
            "-O3",
            *[f"--offload-arch={arch}" for arch in OFFLOAD_ARCHES],
            "-o",
            str(bundle_path),
            str(SRC),
        ]
        print("Compiling bundled HSACO ...")
        run(cmd)

        print("Generating C header ...")
        generate_header(bundle_path, OUT_HEADER)

    print("Done.")


if __name__ == "__main__":
    main()
