#!/usr/bin/env python3
"""Builds the pre-compiled fatbin for the qd.checkpoint() yield-check kernel.

Requires the CUDA toolkit (nvcc) to be installed.

The output is a C header (checkpoint_yield_check_fatbin.h) containing the fatbin as a byte array, which is compiled into
the quadrants binary. Same pattern as the IF-gate fatbin and the graph_do_while condition fatbin -- the user does not
need libcudadevrt.a at runtime.

Usage:
    python scripts/build_checkpoint_yield_check_fatbin.py

See docs/source/user_guide/building_cudagraph_conditional_fatbin.md
"""

import os
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
SRC = REPO_ROOT / "quadrants" / "runtime" / "cuda" / "checkpoint_yield_check.cu"
OUT_HEADER = REPO_ROOT / "quadrants" / "runtime" / "cuda" / "checkpoint_yield_check_fatbin.h"

# Targets cover both pre-Hopper (Turing / Ampere / Ada Lovelace) and Hopper+ (Blackwell). The yield-check kernel itself
# only uses `atomicCAS` and direct pointer writes (no device runtime calls), so it builds fine on every SM target here.
# Pre-Hopper coverage is required because the qd.checkpoint pre-Hopper CUDA path (codegen prologue + flat graph) still
# wires the yield-check kernel as a regular kernel node, just inline after each yielding checkpoint's last body kernel
# instead of inside an IF conditional body. Hopper+ coverage is unchanged from before.
SM_VERSIONS = [75, 80, 86, 89, 90, 100, 120]
SM_TARGETS = [f"-gencode=arch=compute_{v},code=sm_{v}" for v in SM_VERSIONS]


def find_nvcc() -> str:
    nvcc = shutil.which("nvcc")
    if nvcc:
        return nvcc
    candidates = [os.path.join(os.environ[v], "bin", "nvcc") for v in ("CUDA_HOME", "CUDA_PATH") if v in os.environ]
    candidates.append("/usr/local/cuda/bin/nvcc")
    for candidate in candidates:
        if Path(candidate).exists():
            return candidate
    sys.exit("Error: nvcc not found. Install the CUDA toolkit and add it to PATH, or set CUDA_HOME.")


def run(cmd: list[str]) -> None:
    print(f"  {' '.join(cmd)}")
    subprocess.check_call(cmd)


def generate_header(fatbin_path: Path, out_path: Path) -> None:
    fatbin_data = fatbin_path.read_bytes()
    header_lines = [
        "// Auto-generated by scripts/build_checkpoint_yield_check_fatbin.py",
        "// Do not edit manually. Regenerate with that script.",
        "//",
        "// Source: quadrants/runtime/cuda/checkpoint_yield_check.cu",
        f"// SM targets: {', '.join(f'sm_{v}' for v in SM_VERSIONS)}",
        f"// Size: {len(fatbin_data)} bytes",
        "",
        "#pragma once",
        "",
        "#include <cstddef>",
        "",
        "static const unsigned char kCheckpointYieldCheckKernelFatbin[] = {",
    ]
    for i in range(0, len(fatbin_data), 12):
        chunk = fatbin_data[i : i + 12]
        header_lines.append("    " + ", ".join(f"0x{b:02x}" for b in chunk) + ",")
    header_lines.append("};")
    header_lines.append("")
    header_lines.append(f"static const std::size_t kCheckpointYieldCheckKernelFatbinSize = {len(fatbin_data)};")
    header_lines.append("")
    out_path.write_text("\n".join(header_lines), newline="\n")
    print(f"Wrote {out_path} ({len(fatbin_data)} bytes)")


def main() -> None:
    nvcc = find_nvcc()

    with tempfile.TemporaryDirectory() as tmpdir:
        obj_path = Path(tmpdir) / "checkpoint_yield_check.o"
        fatbin_path = Path(tmpdir) / "checkpoint_yield_check.fatbin"

        print("Compiling ...")
        run([nvcc, "-dc", "-rdc=true", *SM_TARGETS, str(SRC), "-o", str(obj_path)])

        print("Device-linking with libcudadevrt ...")
        run([nvcc, "-dlink", *SM_TARGETS, str(obj_path), "-lcudadevrt", "-fatbin", "-o", str(fatbin_path)])

        print("Generating C header ...")
        generate_header(fatbin_path, OUT_HEADER)

    print("Done.")


if __name__ == "__main__":
    main()
