#!/usr/bin/env python3
"""Generate C++ and docs artifacts from the option schema (schema.py).

This runs at C++ build time (see the B1 design doc,
perso_hugh/doc/config_self_documenting_design.md, for the CMake wiring). It
loads ``schema.py`` and emits:

  * compile_config.fields.generated.inc   - struct members + in-class defaults
  * compile_config.bindings.generated.inc - nanobind .def_rw(...) chain

Computed (non-literal) defaults are emitted as in-class initializers too (e.g.
``std::string offline_cache_file_path{get_repo_dir() + "qdcache"};``), matching
how the hand-written struct already does it, so no separate ctor fragment is
needed.

It can also print a markdown reference table (used for eyeballing / as a docs
fallback) so the exact same schema drives code and docs.

The schema stores each option's docs as an attribute docstring, which Python
discards at runtime, so we read names/types/defaults by importing the module and
read the docstrings by parsing its source with ``ast``.

Usage:
  generate.py --emit fields|ctor|bindings|markdown|json   # print to stdout
  generate.py --out-dir <repo-root>                        # write .inc files
"""

from __future__ import annotations

import argparse
import ast
import importlib.util
import json
import sys
import typing
from dataclasses import dataclass
from pathlib import Path

SCHEMA_PATH = Path(__file__).resolve().parent / "schema.py"
BANNER = "// AUTO-GENERATED by tools/config_codegen/generate.py from schema.py. DO NOT EDIT."

# Python annotation base type -> C++ type (used when no Cpp(...) override) and
# -> the Python type name shown in docs. C++ -> Python is 1:1; Python -> C++ is
# not (one Python int, many C++ widths), hence the Cpp(...) override.
_DEFAULT_CPP = {bool: "bool", int: "int", float: "double", str: "std::string"}
_PY_NAME = {bool: "bool", int: "int", float: "float", str: "str"}


@dataclass(frozen=True)
class Option:
    name: str
    cpp_type: str
    py_type: str
    doc: str
    is_computed: bool
    literal_default: object = None  # set when not computed
    computed_expr: str = ""  # set when computed
    computed_doc: str = ""  # set when computed

    def default_display(self) -> str:
        """Human-readable default for docs."""
        if self.is_computed:
            return self.computed_doc
        if isinstance(self.literal_default, bool):
            return "True" if self.literal_default else "False"
        if isinstance(self.literal_default, str):
            return '"' + self.literal_default + '"'
        return str(self.literal_default)


def _import_schema():
    spec = importlib.util.spec_from_file_location("qd_config_schema", SCHEMA_PATH)
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


def _attr_docstrings(path: Path) -> dict[str, str]:
    """Map each Options attribute to the string literal directly above it."""
    tree = ast.parse(path.read_text())
    cls = next(n for n in tree.body if isinstance(n, ast.ClassDef) and n.name == "Options")
    docs: dict[str, str] = {}
    body = cls.body
    for i, stmt in enumerate(body):
        if isinstance(stmt, ast.AnnAssign) and isinstance(stmt.target, ast.Name):
            doc = ""
            prev = body[i - 1] if i >= 1 else None
            if (
                isinstance(prev, ast.Expr)
                and isinstance(prev.value, ast.Constant)
                and isinstance(prev.value.value, str)
            ):
                doc = " ".join(prev.value.value.split())  # collapse newlines/indent
            docs[stmt.target.id] = doc
    return docs


def _resolve_types(mod, annotation) -> tuple[str, str]:
    """(cpp_type, py_type) for an annotation, honoring Annotated[int, Cpp(...)]."""
    if hasattr(annotation, "__metadata__"):  # typing.Annotated[...]
        base = typing.get_args(annotation)[0]
        override = next((m.cpp_type for m in annotation.__metadata__ if isinstance(m, mod.Cpp)), None)
    else:
        base = annotation
        override = None
    return override or _DEFAULT_CPP[base], _PY_NAME[base]


def load_options() -> list[Option]:
    mod = _import_schema()
    docs = _attr_docstrings(SCHEMA_PATH)
    options: list[Option] = []
    for name, annotation in mod.Options.__annotations__.items():
        cpp_type, py_type = _resolve_types(mod, annotation)
        default = getattr(mod.Options, name)
        if isinstance(default, mod.Computed):
            options.append(
                Option(name, cpp_type, py_type, docs.get(name, ""), True,
                       computed_expr=default.cpp_expr, computed_doc=default.doc)
            )
        else:
            options.append(
                Option(name, cpp_type, py_type, docs.get(name, ""), False, literal_default=default)
            )
    return options


_CACHE: list[Option] | None = None


def get_options() -> list[Option]:
    global _CACHE
    if _CACHE is None:
        _CACHE = load_options()
    return _CACHE


def cpp_literal(value) -> str:
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, int):
        return str(value)
    if isinstance(value, str):
        return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'
    raise TypeError(f"unsupported literal type for {value!r}")


def emit_fields() -> str:
    out = [BANNER, ""]
    for opt in get_options():
        out.append(f"  /// {opt.doc}")
        initializer = opt.computed_expr if opt.is_computed else cpp_literal(opt.literal_default)
        out.append(f"  {opt.cpp_type} {opt.name}{{{initializer}}};")
        out.append("")
    return "\n".join(out).rstrip() + "\n"


def emit_bindings() -> str:
    out = [BANNER, ""]
    for opt in get_options():
        out.append(f'      .def_rw("{opt.name}", &CompileConfig::{opt.name})')
    return "\n".join(out).rstrip() + "\n"


def to_rows() -> list[tuple[str, str, str, str]]:
    """(name, py_type, default_display, doc) rows shared with the Sphinx directive."""
    return [(o.name, o.py_type, o.default_display(), o.doc) for o in get_options()]


def emit_markdown() -> str:
    out = ["| Option | Type | Default | Description |", "| --- | --- | --- | --- |"]
    for name, py_type, default, doc in to_rows():
        out.append(f"| `{name}` | `{py_type}` | `{default}` | {doc} |")
    return "\n".join(out) + "\n"


def emit_json() -> str:
    payload = [
        {
            "name": o.name,
            "cpp_type": o.cpp_type,
            "py_type": o.py_type,
            "default": o.computed_doc if o.is_computed else o.literal_default,
            "computed": o.is_computed,
            "doc": o.doc,
        }
        for o in get_options()
    ]
    return json.dumps(payload, indent=2) + "\n"


# Where each generated file lands, relative to the repo root (--out-dir).
OUTPUTS = {
    "quadrants/program/compile_config.fields.generated.inc": emit_fields,
    "quadrants/python/compile_config.bindings.generated.inc": emit_bindings,
}

EMITTERS = {
    "fields": emit_fields,
    "bindings": emit_bindings,
    "markdown": emit_markdown,
    "json": emit_json,
}


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    group = ap.add_mutually_exclusive_group(required=True)
    group.add_argument("--emit", choices=sorted(EMITTERS), help="print one artifact to stdout")
    group.add_argument("--out-dir", type=Path, help="repo root to write the .inc files into")
    args = ap.parse_args(argv)

    if args.emit:
        sys.stdout.write(EMITTERS[args.emit]())
        return 0

    for rel, emitter in OUTPUTS.items():
        dest = args.out_dir / rel
        dest.parent.mkdir(parents=True, exist_ok=True)
        dest.write_text(emitter())
        print(f"wrote {dest}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
