#!/usr/bin/env python3
"""Generate C++ and docs artifacts from the option schema.

This runs at C++ build time (see the B1 design doc,
perso_hugh/doc/config_self_documenting_design.md, for the CMake wiring). It
reads ``schema.py`` and emits:

  * compile_config.fields.generated.inc   - struct members + in-class defaults
  * compile_config.ctor.generated.inc     - ctor assignments for Computed defaults
  * compile_config.bindings.generated.inc - nanobind .def_rw(...) chain

It can also print a markdown reference table (used for eyeballing / as a docs
fallback) so the exact same schema drives code and docs.

Usage:
  generate.py --emit fields|ctor|bindings|markdown|json   # print to stdout
  generate.py --out-dir <repo-root>                        # write .inc files
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from schema import OPTIONS, Computed, Option  # noqa: E402

BANNER = "// AUTO-GENERATED by tools/config_codegen/generate.py from schema.py. DO NOT EDIT."


def cpp_literal(value) -> str:
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, int):
        return str(value)
    if isinstance(value, str):
        return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'
    raise TypeError(f"unsupported literal type for {value!r}")


def emit_fields() -> str:
    out = [BANNER, ""]
    for opt in OPTIONS:
        out.append(f"  /// {opt.doc}")
        if isinstance(opt.default, Computed):
            out.append(f"  {opt.cpp_type} {opt.name};  // default: {opt.default.doc}")
        else:
            out.append(f"  {opt.cpp_type} {opt.name}{{{cpp_literal(opt.default)}}};")
        out.append("")
    return "\n".join(out).rstrip() + "\n"


def emit_ctor() -> str:
    out = [BANNER, "", "// Computed (non-literal) defaults, assigned in CompileConfig::CompileConfig()."]
    for opt in OPTIONS:
        if isinstance(opt.default, Computed):
            out.append(f"  {opt.name} = {opt.default.cpp_expr};")
    return "\n".join(out).rstrip() + "\n"


def emit_bindings() -> str:
    out = [BANNER, ""]
    for opt in OPTIONS:
        out.append(f'      .def_rw("{opt.name}", &CompileConfig::{opt.name})')
    return "\n".join(out).rstrip() + "\n"


def to_rows() -> list[tuple[str, str, str, str]]:
    """(name, py_type, default_display, doc) rows shared with the Sphinx directive."""
    return [(o.name, o.py_type, o.default_display(), o.doc) for o in OPTIONS]


def emit_markdown() -> str:
    rows = to_rows()
    out = ["| Option | Type | Default | Description |", "| --- | --- | --- | --- |"]
    for name, py_type, default, doc in rows:
        out.append(f"| `{name}` | `{py_type}` | `{default}` | {doc} |")
    return "\n".join(out) + "\n"


def emit_json() -> str:
    payload = [
        {
            "name": o.name,
            "cpp_type": o.cpp_type,
            "py_type": o.py_type,
            "default": o.default.doc if isinstance(o.default, Computed) else o.default,
            "computed": isinstance(o.default, Computed),
            "doc": o.doc,
        }
        for o in OPTIONS
    ]
    return json.dumps(payload, indent=2) + "\n"


# Where each generated file lands, relative to the repo root (--out-dir).
OUTPUTS = {
    "quadrants/program/compile_config.fields.generated.inc": emit_fields,
    "quadrants/program/compile_config.ctor.generated.inc": emit_ctor,
    "quadrants/python/compile_config.bindings.generated.inc": emit_bindings,
}

EMITTERS = {
    "fields": emit_fields,
    "ctor": emit_ctor,
    "bindings": emit_bindings,
    "markdown": emit_markdown,
    "json": emit_json,
}


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    group = ap.add_mutually_exclusive_group(required=True)
    group.add_argument("--emit", choices=sorted(EMITTERS), help="print one artifact to stdout")
    group.add_argument("--out-dir", type=Path, help="repo root to write the .inc files into")
    args = ap.parse_args(argv)

    if args.emit:
        sys.stdout.write(EMITTERS[args.emit]())
        return 0

    for rel, emitter in OUTPUTS.items():
        dest = args.out_dir / rel
        dest.parent.mkdir(parents=True, exist_ok=True)
        dest.write_text(emitter())
        print(f"wrote {dest}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
