# type: ignore
"""Per-thread unpacked-storage layout for ``@qd.dataclass`` fields.

The user-facing surface is the ``unpacked=True`` kwarg on :func:`quadrants.types.vector` -- see
:doc:`/user_guide/matrix_vector` and ``VectorType.__init__`` in ``lang/matrix.py``. This module contains the internal
machinery consumed by ``StructType.__init__`` and the AST transformer.

Why an unpacked layout: under high register pressure (e.g. several concurrent 32x32 tiles in a Cholesky + triangular
solve), LLVM's SROA + ``mem2reg`` can fail to decompose a packed ``alloca``, causing the whole group to spill to local
memory as a unit. An unpacked layout puts each slot in its own ``alloca`` up front, so the optimiser can promote slots
independently and spill only the ones it has to.

Today this affects only how ``obj.r[i]`` accesses lower -- the AST transformer rewrites ``obj.r[i]`` (for python-int /
``qd.static``-resolved ``i``) into a direct reference to a synthetic scalar field ``obj._r{i}``. Materialising
``obj.r`` itself as a vector value (for arithmetic, swizzle, reductions, runtime indexing) is a follow-up; for now,
the supported access pattern is indexed reads/writes only.

Internal (used by ``StructType`` and the AST transformer):
- ``_expand_unpacked_naming(group, i)``    -- synthetic-field naming convention
- ``_UnpackedVectorRef``                   -- transient proxy yielded by attribute access
- ``expand_unpacked_into(...)``            -- per-member expansion driver, called from ``StructType.__init__``
- ``_check_no_unpacked_collision(...)``    -- guard against user-declared fields clashing with synthetic names
- ``attach_unpacked_groups(...)``          -- per-instance metadata tagging for Struct / StructField

This module has no dependency on ``struct.py``; ``struct.py`` imports from here.
"""

import numpy as np

from quadrants.lang.exception import QuadrantsSyntaxError


def _expand_unpacked_naming(group_name, index):
    """Naming convention for the synthetic scalar fields of an unpacked-vector group.

    Public-ish so the AST transformer can mirror this without a circular import on ``struct``.
    """
    return f"_{group_name}{index}"


def _check_no_unpacked_collision(name, members):
    """Reject a member name that collides with a synthetic field generated by an earlier ``unpacked=True`` vector
    field in the same struct. Called from ``StructType.__init__`` for each non-unpacked member; the in-loop branch
    handles the reverse case (synthetic field colliding with an already-declared member)."""
    if name in members:
        raise QuadrantsSyntaxError(
            f"member name {name!r} collides with a synthetic field generated by an earlier vector field declared "
            f"with ``unpacked=True``. Rename the colliding field or the unpacked vector."
        )


def expand_unpacked_into(group_name, vector_type, members, unpacked_groups, elements, cook_dtype):
    """Expand a ``qd.types.vector(N, dtype, unpacked=True)`` field into ``N`` synthetic scalar members.

    Mutates ``members``, ``unpacked_groups``, and ``elements`` in place. Called from ``StructType.__init__``; kept as
    a free function here (rather than a method on ``StructType``) so the unpacked-layout feature surface lives in one
    module. ``cook_dtype`` is injected to avoid an import cycle (``struct.py`` -> this module -> ``lang.util``).
    """
    count = vector_type.n
    cooked = cook_dtype(vector_type.dtype)
    unpacked_groups[group_name] = (count, cooked, _expand_unpacked_naming)
    for i in range(count):
        sub = _expand_unpacked_naming(group_name, i)
        # Reject collisions with previously-declared fields so the user gets a clear error rather than a silent
        # overwrite that would route ``s.r[i]`` to the wrong storage. Note this only catches collisions with members
        # already processed in the caller's loop; the reverse order (synthetic colliding with a later-declared member)
        # is caught by ``_check_no_unpacked_collision`` in the caller's other branches.
        if sub in members:
            raise QuadrantsSyntaxError(
                f"unpacked vector field {group_name!r} would expand to a synthetic field {sub!r} that collides with "
                f"another member of the same struct. Rename the colliding field or the unpacked vector."
            )
        members[sub] = cooked
        elements.append([cooked, sub])


def attach_unpacked_groups(target, unpacked_groups):
    """Tag a ``Struct`` expression-object or ``StructField`` with an unpacked-group dictionary so the AST transformer
    can rewrite ``obj.{group}[i]`` (or ``f[i].{group}[k]``) into direct synthetic-field references.

    The transformer inspects the instance (not the ``StructType``), so the metadata has to ride on every struct /
    field that the type produces -- including ones rehydrated through nested ``cast()`` calls,
    ``filled_with_scalar()``, and per-index ``impl.subscript`` paths. ``setattr`` (rather than attribute assignment)
    sidesteps pyright's ``reportAttributeAccessIssue``: ``Struct`` doesn't statically declare this attribute.

    No-op when there are no groups, so the call site doesn't have to guard.
    """
    if unpacked_groups:
        setattr(target, "_qd_unpacked_groups", unpacked_groups)


class _UnpackedVectorRef:
    """Transient proxy returned by the AST transformer for ``obj.{group}`` where ``group`` is a vector field declared
    with ``unpacked=True`` on the struct type.

    Only valid as the value of a Subscript node: ``obj.{group}[i]``. Resolved by ``ASTTransformer.build_Subscript``
    to a direct reference to the synthetic scalar field ``_{group}{i}`` when ``i`` is a python-int /
    ``qd.static``-resolved integer.

    Used as a not-an-Expr marker; any attempt to use it as a value raises.
    """

    _qd_is_unpacked_vector_ref = True

    def __init__(self, struct, group_name: str, count: int, dtype, naming_fn):
        self._qd_struct = struct
        self._qd_group_name = group_name
        self._qd_count = count
        self._qd_dtype = dtype
        self._qd_naming_fn = naming_fn

    def _qd_field_for(self, index: int):
        if not isinstance(index, (int, np.integer)):
            raise QuadrantsSyntaxError(
                f"unpacked vector {self._qd_group_name}[i] requires a python-int index "
                f"(possibly via qd.static); got runtime index of type {type(index).__name__}"
            )
        i = int(index)
        if i < 0 or i >= self._qd_count:
            raise QuadrantsSyntaxError(
                f"unpacked vector index out of bounds: {self._qd_group_name}[{i}] (count={self._qd_count})"
            )
        field_name = self._qd_naming_fn(self._qd_group_name, i)
        return getattr(self._qd_struct, field_name)

    def __repr__(self) -> str:  # pragma: no cover - debug only
        return f"<unpacked_vector_ref group={self._qd_group_name!r} count={self._qd_count} dtype={self._qd_dtype}>"
