// Auto-generated by scripts/build_checkpoint_yield_check_hsaco.py
// Do not edit manually. Regenerate with that script.
//
// PLACEHOLDER -- this header is the build-time fallback that ships in source control before
// the first real build on a machine with ROCm. Build the real header by running:
//
//   python scripts/build_checkpoint_yield_check_hsaco.py
//
// on a machine with hipcc installed (see amddesktop / amdcloud in `~/.cursor/skills/`).
// Until that's done the AMDGPU qd.checkpoint path falls back through
// `GraphManager::try_launch` and the runtime aborts on `hipModuleLoadData` because the
// placeholder bundle is just a single zero byte.

#pragma once

#include <cstddef>

static const unsigned char kCheckpointYieldCheckKernelHsaco[] = {0x00};

static const std::size_t kCheckpointYieldCheckKernelHsacoSize = 1;
